### ISSUE TITLE
Adjust forcefield strength

### ISSUE THREAD

**Issue by Avenred** [BGHDDevelopment/ForceField#4]
Is there any way to adjust the strength of the forcefield in the config?

**Comment by BGHDDevelopment** [comment]
The range is an option in the config.

**Comment by Avenred** [comment]
yes, but players are thrown back really far into the air, often taking fall damage. is there any way to adjust the velocity?

**Comment by BGHDDevelopment** [comment]
That is hardcoded on line 70 of the ForceField class at this point. Most people use this in Hub’s so fall damage is disabled.
